//! The pinned plain-text part and the pinned assembled message (alo Campaigns,
//! ADR 0044, C3.3).
//!
//! The harness is C3.2's, deliberately: same `UPDATE_GOLDENS` switch, same
//! `v1` naming rule, same reason. *The same blocks must produce the same
//! output, so a regression is visible rather than discovered by a customer's
//! recipients* — and a text part fails even more quietly than an HTML one. A
//! table that stopped aligning, a wrap that started breaking URLs, a heading
//! whose underline drifted by one character: none of it throws, and all of it
//! arrives as a letter that looks like it was generated by a machine that did
//! not care.
//!
//! **The letter pinned here is the letter `campaign_html_golden.rs` pins**, so
//! the two files can be read side by side as the two halves of one mail.
//!
//! `campaign_mime_v1_letter.mime` is the whole assembled entity, CRLF and all.
//! It is marked `-text` in `.gitattributes` for the reason the bank fixtures
//! there are: a golden whose line endings git rewrote would stop being the
//! thing the reader is tested against, and in a MIME body the line ending *is*
//! the format.
//!
//! To re-bless after a deliberate change: `UPDATE_GOLDENS=1 cargo nextest run
//! -p alo-store campaign_text_golden`, then **read the diff** — that reading is
//! the test, not the green tick afterwards.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::fs;
use std::path::PathBuf;

use alo_store::campaign_unsubscribe_link::UnsubscribeInvitation;
use alo_store::{
    CAMPAIGN_CONTENT_SCHEMA_VERSION, CAMPAIGN_HEADER_LINE_MAX, CAMPAIGN_MIME_LINE_MAX,
    CAMPAIGN_TEXT_WIDTH_COLS, CampaignContent, CampaignLetter, render_campaign_html,
    render_campaign_message, render_campaign_text,
};
use serde_json::{Value, json};

/// The way out the letter must carry (C2.4/C2.5). Not English on purpose: the
/// words belong to the caller, and a golden pinning "Unsubscribe" would read as
/// though they belonged to the renderer.
fn unsub() -> UnsubscribeInvitation {
    UnsubscribeInvitation {
        url: "https://alo.test/u/9tOKENx".to_owned(),
        topic: Some("Nieuwsbrief".to_owned()),
        link_text: "Uitschrijven".to_owned(),
    }
}

fn body(blocks: Value) -> CampaignContent {
    CampaignContent::from_value(json!({
        "schema_version": CAMPAIGN_CONTENT_SCHEMA_VERSION,
        "blocks": blocks,
    }))
    .expect("every fixture in this file must pass the write gate")
}

fn golden_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/golden")
        .join(name)
}

fn assert_golden(name: &str, rendered: &str) {
    let path = golden_path(name);
    if std::env::var("UPDATE_GOLDENS").is_ok() {
        fs::create_dir_all(path.parent().expect("a golden lives in a directory"))
            .expect("the golden directory is writable");
        fs::write(&path, rendered).expect("the golden is writable");
        return;
    }
    let expected = fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("missing golden {name}; run with UPDATE_GOLDENS=1"));
    assert_eq!(
        rendered, expected,
        "{name} drifted; re-bless with UPDATE_GOLDENS=1 and read the diff — a recipient will not \
         tell you which half of the change was the mistake"
    );
}

/// The letter `campaign_html_golden.rs` pins, block for block.
fn newsletter() -> CampaignContent {
    body(json!([
        { "type": "heading", "id": "b1", "level": 1, "text": "Spring prices" },
        {
            "type": "paragraph",
            "id": "b2",
            "text": "Beste klant,\nvanaf maandag gelden de prijzen hieronder. Alles is per liter.",
        },
        { "type": "paragraph", "id": "b3", "text": "" },
        {
            "type": "table",
            "id": "b4",
            "rows": [
                ["Product", "Prijs", "Vanaf"],
                ["Olijfolie — extra vierge", "12,50 €", "2 maart"],
                ["Zonnebloemolie", "6,00 €", "2 maart"],
            ],
        },
        { "type": "heading", "id": "b5", "level": 2, "text": "Bestellen via de API" },
        {
            "type": "code",
            "id": "b6",
            "code": "curl https://api.alo.test/orders \\\n  -H 'Accept: application/json' \\\n  -d '{\"sku\": \"olive-1l\"}'   # één liter",
            "language": "bash",
        },
        {
            "type": "paragraph",
            "id": "b7",
            "text": "Met vriendelijke groet,\nNordwind & Co",
        },
    ]))
}

/// A table nobody can draw in 72 columns, and a paragraph carrying the kind of
/// URL that must never be wrapped. This is the fixture for the item's real
/// work — the fallback that keeps a price list readable without a font.
fn wide() -> CampaignContent {
    body(json!([
        {
            "type": "table",
            "id": "b1",
            "rows": [
                ["Product", "Omschrijving", "Prijs per liter", "Vanaf"],
                [
                    "Olijfolie",
                    "Extra vierge, eerste koude persing, Kalamata",
                    "12,50 €",
                    "2 maart",
                ],
                ["Zonnebloemolie", "Geraffineerd, neutraal van smaak", "6,00 €", "2 maart"],
            ],
        },
        {
            "type": "paragraph",
            "id": "b2",
            "text": "Bestel via https://alo.test/campaigns/spring-prices-2026/orders?reference=NL-2026-0042 en de prijs geldt tot het einde van de maand.",
        },
    ]))
}

/// Text that would break out of a document if this were HTML — pinned here to
/// show that in the text part it is simply text, entities and angle brackets
/// and all, and that nothing was escaped into something the reader did not
/// write.
fn hostile() -> CampaignContent {
    body(json!([
        { "type": "heading", "id": "b1", "level": 2, "text": "<script>alert('x')</script> & Co" },
        {
            "type": "paragraph",
            "id": "b2",
            "text": "She said \"it's <b>fine</b>\" &amp; left — 5 > 3.",
        },
        {
            "type": "table",
            "id": "b3",
            "rows": [
                ["</th></tr></table>", "\"quoted\""],
                ["<img src=x onerror=alert(1)>", "a & b"],
            ],
        },
        {
            "type": "code",
            "id": "b4",
            "code": "</td></tr></table><script>alert(1)</script>\n\tconst x = '<a href=\"#\">';",
            "language": "html",
        },
    ]))
}

fn text(content: &CampaignContent) -> String {
    render_campaign_text(content, &unsub()).expect("a body that passed the write gate renders")
}

/// The whole text part, pinned. This is the file to read when a change to the
/// renderer needs reviewing — and the one to read aloud when deciding whether
/// the letter still reads as a letter.
#[test]
fn a_whole_letter_is_pinned_line_for_line() {
    assert_golden("campaign_text_v1_letter.txt", &text(&newsletter()));
}

/// The fallback, pinned: a table too wide for columns becomes one block per
/// row, and a URL longer than the column sits alone and whole.
#[test]
fn a_table_that_cannot_be_drawn_is_pinned_as_the_blocks_it_becomes() {
    let rendered = text(&wide());
    assert_golden("campaign_text_v1_wide.txt", &rendered);

    // The two facts a reader should not have to reconstruct from the diff.
    assert!(
        rendered.contains("Omschrijving: Extra vierge, eerste koude persing, Kalamata"),
        "{rendered}"
    );
    assert!(
        rendered.lines().any(|line| line
            == "https://alo.test/campaigns/spring-prices-2026/orders?reference=NL-2026-0042"),
        "the URL must sit alone and whole: {rendered}"
    );
}

/// The text part is text: no escaping, no markup, and nothing the writer did
/// not type.
#[test]
fn a_hostile_body_is_pinned_so_the_text_part_stays_text() {
    let rendered = text(&hostile());
    assert_golden("campaign_text_v1_hostile.txt", &rendered);

    assert!(
        rendered.contains("<script>alert('x')</script> & Co"),
        "{rendered}"
    );
    assert!(
        !rendered.contains("&lt;"),
        "an HTML escape leaked in: {rendered}"
    );
    assert!(!rendered.contains("<br />"), "markup leaked in: {rendered}");
}

/// The assembled entity, byte for byte: boundary, headers, both encodings and
/// the closing delimiter. An encoding regression is a letter that arrives as
/// `=3D` soup in somebody's inbox, and this diff is what catches it first.
#[test]
fn the_assembled_message_is_pinned_byte_for_byte() {
    let assembled = render_campaign_message(&CampaignLetter {
        subject: "Nieuwe prijzen vanaf maandag",
        preheader: Some("Olijfolie 12,50 € — geldig vanaf 2 maart"),
        content: &newsletter(),
        unsubscribe: &unsub(),
    })
    .expect("a validated letter assembles");

    let pinned = format!(
        "Content-Type: {}\r\n\r\n{}",
        assembled.content_type, assembled.body
    );
    assert_golden("campaign_mime_v1_letter.mime", &pinned);
}

/// A golden pins bytes and would happily pin a broken message. This walks the
/// pinned file as a message: CRLF everywhere, every line inside the RFC 2045
/// cap, three delimiters, and both parts decoding back to exactly what the two
/// renderers produce today.
///
/// It is also what proves the file survived git: a `.mime` golden whose CRLFs
/// were normalised would fail here rather than quietly become a different
/// format.
#[test]
fn the_pinned_message_is_still_a_message() {
    let pinned = fs::read_to_string(golden_path("campaign_mime_v1_letter.mime")).expect(
        "the pinned message is readable — on the blessing run itself it may not have been written \
         yet, so run once more without UPDATE_GOLDENS",
    );

    assert!(
        !pinned.replace("\r\n", "").contains('\n'),
        "a bare line feed in a MIME body — git normalised the golden"
    );

    let (header, body) = pinned
        .split_once("\r\n\r\n")
        .expect("the pinned file is a content type and an entity");
    // The header is a header — RFC 5322's 78 octets is what a sender may write
    // unfolded; the body is quoted-printable and bound by RFC 2045's 76.
    assert!(
        header.len() <= CAMPAIGN_HEADER_LINE_MAX,
        "a header of {} octets: {header}",
        header.len()
    );
    for line in body.split("\r\n") {
        assert!(
            line.len() <= CAMPAIGN_MIME_LINE_MAX,
            "a line of {} octets: {line:?}",
            line.len()
        );
    }

    let boundary = header
        .split("boundary=\"")
        .nth(1)
        .and_then(|rest| rest.strip_suffix('"'))
        .expect("the boundary is in the content type");
    assert_eq!(
        body.matches(boundary).count(),
        3,
        "two openers and a closer, and the boundary in neither part"
    );

    let letter = CampaignLetter {
        subject: "Nieuwe prijzen vanaf maandag",
        preheader: Some("Olijfolie 12,50 € — geldig vanaf 2 maart"),
        content: &newsletter(),
        unsubscribe: &unsub(),
    };
    let parts = decode_parts(body, boundary);
    assert_eq!(parts.len(), 2, "two alternatives");
    assert_eq!(
        parts[0],
        render_campaign_text(letter.content, &unsub()).expect("renders"),
        "the pinned text part is not what the renderer produces today"
    );
    assert_eq!(
        parts[1],
        render_campaign_html(&letter).expect("renders"),
        "the pinned HTML part is not what the renderer produces today"
    );
}

/// Every line of the pinned text part fits the column, except the ones that
/// are allowed not to: a URL too long to break, and a line of code, which is
/// never wrapped because a wrapped command fails when it is pasted.
#[test]
fn the_pinned_letter_fits_the_column_it_was_wrapped_to() {
    for (name, rendered) in [
        ("letter", text(&newsletter())),
        ("wide", text(&wide())),
        ("hostile", text(&hostile())),
    ] {
        let mut in_code = false;
        for line in rendered.lines() {
            if line.starts_with('[') && line.ends_with(']') {
                in_code = true;
            } else if line.is_empty() {
                in_code = false;
            }
            let single_word = line.split_whitespace().count() <= 1;
            assert!(
                line.chars().count() <= CAMPAIGN_TEXT_WIDTH_COLS || in_code || single_word,
                "the {name} letter ran past the column on a line that could have wrapped: \
                 {line:?}"
            );
            assert_eq!(
                line,
                line.trim_end(),
                "the {name} letter has a line ending in whitespace: {line:?}"
            );
        }
    }
}

/// The goldens are named `v1` because they describe what version 1 of the block
/// model renders to. A bump gets its own files under its own name — re-blessing
/// these in place would destroy the record of what the previous model produced.
#[test]
fn the_goldens_are_pinned_to_the_model_they_were_blessed_against() {
    assert_eq!(
        CAMPAIGN_CONTENT_SCHEMA_VERSION, 1,
        "the block model moved past the version these goldens are named for — add \
         campaign_text_v{CAMPAIGN_CONTENT_SCHEMA_VERSION}_*.txt beside them, do not re-bless the \
         v1 files"
    );
}

/// Splits an entity into its decoded parts. Written from RFC 2045 §6.7 rather
/// than by calling the encoder backwards, so the pinned bytes are checked
/// against the standard instead of against the code that wrote them.
fn decode_parts(body: &str, boundary: &str) -> Vec<String> {
    let mut parts = Vec::new();
    for chunk in body.split(&format!("--{boundary}")).skip(1) {
        if chunk.starts_with("--") {
            break; // the closing delimiter
        }
        let payload = chunk
            .split_once("\r\n\r\n")
            .expect("a part has headers and a body")
            .1;
        let payload = payload.strip_suffix("\r\n").unwrap_or(payload);
        parts.push(decode_quoted_printable(payload).replace("\r\n", "\n"));
    }
    parts
}

/// A line ending in a lone `=` is a soft break and joins the next one; an `=XX`
/// triple is one byte; everything else is itself.
fn decode_quoted_printable(encoded: &str) -> String {
    let lines: Vec<&str> = encoded.split("\r\n").collect();
    let mut out: Vec<u8> = Vec::with_capacity(encoded.len());
    for (index, line) in lines.iter().enumerate() {
        let (content, soft) = match line.strip_suffix('=') {
            Some(rest) => (rest, true),
            None => (*line, false),
        };
        let bytes = content.as_bytes();
        let mut at = 0;
        while at < bytes.len() {
            if bytes[at] == b'=' {
                let hex =
                    std::str::from_utf8(&bytes[at + 1..at + 3]).expect("an =XX triple is ascii");
                out.push(u8::from_str_radix(hex, 16).expect("an =XX triple is hex"));
                at += 3;
            } else {
                out.push(bytes[at]);
                at += 1;
            }
        }
        if !soft && index + 1 < lines.len() {
            out.extend_from_slice(b"\r\n");
        }
    }
    String::from_utf8(out).expect("quoted-printable decodes to the utf-8 input")
}
