import type { FormEvent, ReactNode } from "react";
import { X, type LucideIcon } from "lucide-react";
import { Button } from "../ds";
import { strings } from "../i18n";
import { ErrorBanner } from "./ErrorBanner";

export function DialogFrame({ Icon, title, subtitle, error, busy, canSubmit, submitLabel, onClose, onSubmit, wide = false, children }: { Icon: LucideIcon; title: string; subtitle: string; error: string | null; busy: boolean; canSubmit: boolean; submitLabel: string; onClose: () => void; onSubmit: () => void; wide?: boolean; children: ReactNode }) {
  function submit(event: FormEvent) { event.preventDefault(); if (!busy && canSubmit) onSubmit(); }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-overlay p-6 max-sm:p-3" role="presentation" onMouseDown={onClose}><form className={`flex max-h-[calc(100dvh-3rem)] w-full ${wide ? "max-w-4xl" : "max-w-2xl"} flex-col overflow-hidden rounded-xl border border-subtle bg-surface shadow-lg max-sm:max-h-[calc(100dvh-1.5rem)]`} role="dialog" aria-modal="true" aria-label={title} onSubmit={submit} onMouseDown={(event) => event.stopPropagation()} onKeyDown={(event) => { if (event.key === "Escape") onClose(); }}><div className="flex shrink-0 items-start gap-3 border-b border-subtle px-5 py-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-[var(--accent-soft)] text-accent" aria-hidden="true"><Icon size={19} /></span><div className="min-w-0 flex-1"><h2 className="m-0 text-lg font-semibold text-primary">{title}</h2><p className="mt-1 text-sm leading-relaxed text-secondary">{subtitle}</p></div><button type="button" className="flex size-9 shrink-0 items-center justify-center rounded-lg text-tertiary transition-colors hover:bg-raised hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent" onClick={onClose} aria-label={strings.billingCancel}><X size={18} /></button></div><div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto p-5">{error !== null && <ErrorBanner message={error} />}{children}</div><div className="flex shrink-0 justify-end gap-2 border-t border-subtle bg-surface px-5 py-4"><Button variant="ghost" onClick={onClose} disabled={busy}>{strings.billingCancel}</Button><Button type="submit" disabled={busy || !canSubmit}>{submitLabel}</Button></div></form></div>;
}
