import { useEffect,useState } from "react";
import { BookOpen,X } from "lucide-react";
import { IconButton,Modal,Spinner,Table,Td,Th } from "../ds";
import { strings } from "../i18n";
import { financeMessage,useFinanceApi } from "./api";
import { amountLabel } from "./format";
import { ErrorBanner } from "./parts";
import type { AccountLedger } from "./types";

export function LedgerDialog({accountId,name,currency,from,to,onClose}:{accountId:string;name:string;currency:string;from:string;to:string;onClose:()=>void}){const api=useFinanceApi();const [ledger,setLedger]=useState<AccountLedger|null>(null);const [error,setError]=useState<string|null>(null);useEffect(()=>{void api.accountLedger(accountId,from,to).then(setLedger).catch(reason=>setError(financeMessage(reason,strings.financeLedgerLoadFailed)));},[api,accountId,from,to]);return <Modal wide tall title={strings.financeLedgerTitle(name)} icon={<BookOpen className="size-5"/>} actions={<IconButton label={strings.close} icon={<X className="size-4"/>} onClick={onClose}/>} onClose={onClose}>{error&&<ErrorBanner message={error}/>} {!ledger?<div className="grid flex-1 place-items-center"><Spinner size={22}/></div>:<div className="min-h-0 flex-1 overflow-auto rounded-xl border border-subtle"><Table label={strings.financeLedgerTitle(name)}><thead><tr><Th>{strings.financeDate}</Th><Th>{strings.financeDescription}</Th><Th numeric>{strings.financeReportAmount}</Th><Th numeric>{strings.financeRunningBalance}</Th></tr></thead><tbody><tr><Td colSpan={3}>{strings.financeOpeningBalance}</Td><Td numeric>{amountLabel(ledger.openingCents,currency)}</Td></tr>{ledger.lines.map(line=><tr key={line.id}><Td>{line.date}</Td><Td><span className="block font-medium text-primary">{line.entryMemo||line.memo||line.kind}</span><span className="text-xs text-tertiary">{line.kind}</span></Td><Td numeric>{amountLabel(line.baseCents,currency)}</Td><Td numeric>{amountLabel(line.runningCents,currency)}</Td></tr>)}</tbody><tfoot><tr><Th scope="row" colSpan={3}>{strings.financeClosingBalance}</Th><Td numeric>{amountLabel(ledger.closingCents,currency)}</Td></tr></tfoot></Table>{ledger.truncated&&<p className="m-3 text-sm text-warning">{strings.financeLedgerTruncated}</p>}</div>}</Modal>}
