// Extract the full KaTeX math-symbol catalogue from its source table and emit
// TypeScript EqSymbol entries, bucketed into the editor's categories, for every
// symbol not already hand-curated. Run: node scripts/gen-symbols.mjs
import { readFileSync } from "node:fs";

const KATEX = "node_modules/katex/src/symbols.ts";
const CUR = "src/authoring/equationSymbols.ts";

const src = readFileSync(KATEX, "utf8");

// defineSymbol(mode, font, group, replace, name, acceptUnicodeChar?)
const re =
  /defineSymbol\(\s*math\s*,\s*\w+\s*,\s*(\w+)\s*,\s*("(?:[^"\\]|\\.)*")\s*,\s*("(?:[^"\\]|\\.)*")/g;

const arrowRe =
  /(arrow|harpoon|mapsto|leadsto|hook|rightleft|leftright|updown|nearrow|nwarrow|searrow|swarrow|curvearrow|twohead|squigarrow|iff|implies|longmapsto|multimap|upuparrows|downdownarrows)/i;
const setRe =
  /(subset|supset|sqsubset|sqsupset|^in$|^ni$|notin|owns|vdash|dashv|models|vDash|Vdash|Vvdash|complement|^top$|^bot$|because|therefore|forall|exists|nexists|^neg$|land$|lor$|emptyset|varnothing)/i;
const calcRe =
  /(partial|nabla|infty|prime|aleph|beth|gimel|daleth|hbar|hslash|^ell$|^wp$|^Re$|^Im$|Finv|Game|^eth$|angle|triangle|square|diamond|blacksquare|blacktriangle|surd|^mho$|backprime|nabla|circledS)/i;

const GREEK = new Set([
  "alpha", "beta", "gamma", "delta", "epsilon", "varepsilon", "zeta", "eta", "theta",
  "vartheta", "iota", "kappa", "varkappa", "lambda", "mu", "nu", "xi", "pi", "varpi",
  "rho", "varrho", "sigma", "varsigma", "tau", "upsilon", "phi", "varphi", "chi", "psi",
  "omega", "digamma", "Gamma", "Delta", "Theta", "Lambda", "Xi", "Pi", "Sigma", "Upsilon",
  "Phi", "Psi", "Omega",
]);

function bucket(group, name) {
  if (GREEK.has(name)) return "greek";
  switch (group) {
    case "bin": return "operators";
    case "op": return "bigops";
    case "open": case "close": return "delimiters";
    case "punct": case "inner": return "misc";
    case "accent": return "structures";
    case "rel":
      if (arrowRe.test(name)) return "arrows";
      if (setRe.test(name)) return "sets";
      return "relations";
    case "mathord": case "textord":
      if (arrowRe.test(name)) return "arrows";
      if (setRe.test(name)) return "sets";
      if (calcRe.test(name)) return "calculus";
      return "misc";
    default: return null; // spacing etc.
  }
}

// Commands already curated (skip those — keep the nice hand-written versions).
// Covers both object-literal entries (`latex: "\\x"`) and the g("ch","name","\\x")
// helper form.
const curatedSrc = readFileSync(CUR, "utf8");
const curated = new Set();
for (const m of curatedSrc.matchAll(/latex:\s*("(?:[^"\\]|\\.)*")/g)) {
  curated.add(JSON.parse(m[1]));
}
for (const m of curatedSrc.matchAll(
  /\bg\(\s*"(?:[^"\\]|\\.)*"\s*,\s*"(?:[^"\\]|\\.)*"\s*,\s*("(?:[^"\\]|\\.)*")/g,
)) {
  curated.add(JSON.parse(m[1]));
}

const seen = new Set();
const byCat = {};
let m;
while ((m = re.exec(src)) !== null) {
  const group = m[1];
  const replace = JSON.parse(m[2]);
  const name = JSON.parse(m[3]); // e.g. "\\oplus"
  if (!/^\\[a-zA-Z]+$/.test(name)) continue; // word commands only
  if (curated.has(name) || seen.has(name)) continue;
  seen.add(name);
  const label = name.slice(1); // strip backslash
  const cat = bucket(group, label);
  if (cat === null) continue;
  let ch = replace ?? label;
  let insert, caret;
  if (group === "accent") {
    ch = `◌${replace ?? ""}`; // dotted circle + combining accent
    insert = `${name}{}`;
    caret = -1;
  } else if (group === "op") {
    insert = `${name}_{}^{}`;
    caret = -3;
  }
  (byCat[cat] ??= []).push({ ch, name: label, latex: name, insert, caret });
}

// Emit a TS module mapping category id -> the extra (auto-generated) symbols.
const order = [
  "structures", "greek", "operators", "relations", "arrows", "bigops", "sets",
  "calculus", "delimiters", "misc",
];
let total = 0;
const lines = [
  "// AUTO-GENERATED by scripts/gen-symbols.mjs — every remaining KaTeX math",
  "// symbol not hand-curated in equationSymbols.ts, so the picker lists the full",
  "// KaTeX catalogue. Do not edit by hand; re-run `node scripts/gen-symbols.mjs`.",
  'import type { EqSymbol } from "./equationSymbols";',
  "",
  "export const EXTRA: Record<string, EqSymbol[]> = {",
];
for (const cat of order) {
  const list = byCat[cat] ?? [];
  total += list.length;
  lines.push(`  ${cat}: [`);
  for (const s of list) {
    const parts = [
      `ch: ${JSON.stringify(s.ch)}`,
      `name: ${JSON.stringify(s.name)}`,
      `latex: ${JSON.stringify(s.latex)}`,
    ];
    if (s.insert !== undefined) parts.push(`insert: ${JSON.stringify(s.insert)}`);
    if (s.caret !== undefined) parts.push(`caret: ${s.caret}`);
    lines.push(`    { ${parts.join(", ")} },`);
  }
  lines.push("  ],");
}
lines.push("};", "");
const { writeFileSync } = await import("node:fs");
writeFileSync("src/authoring/equationSymbolsExtra.ts", lines.join("\n"));
console.error(`wrote equationSymbolsExtra.ts — TOTAL NEW: ${total} (curated skipped: ${curated.size})`);
