// Public surface of the shared JMAP area.
export { JmapClient, JmapError } from "./client";
export type { AppPassword, PushSettings, PushSubscriptionRecord } from "./client";
export { useJmapClient } from "./useJmapClient";
export {
  MAIL_CAPABILITY,
  KEYWORD_SEEN,
  KEYWORD_FLAGGED,
  CATEGORY_KEYWORD_PREFIX,
  categoryKeyword,
  categoryIdOf,
  type Category,
  type Calendar,
  type CalendarEvent,
  type CalendarGrant,
  type CalendarInvitation,
  type RsvpResponse,
  type EventInput,
  type Contact,
  type ContactField,
  type ContactDraft,
  type Mailbox,
  type EmailHeaders,
  type EmailFull,
  type EmailBodyPart,
  type EmailBodyValue,
  type EmailAttachment,
  type EmailAddress,
  type MessageAuthentication,
  type ListUnsubscribe,
  type MailFilterRule,
  type FilterCondition,
  type FilterAction,
  type FilterField,
  type FilterOp,
  type FilterMatch,
  type AiProvider,
  type AdminUser,
  type AppModuleId,
  type TenantRole,
  type UserModuleAccess,
  type AdminGroup,
  type SecurityCheck,
  type AuditEntry,
  type ControlTenant,
  type ControlDomain,
  type Session,
  type FreeBusyPerson,
  type WorkingHours,
  type Task,
  type TaskProject,
  type TaskDetailData,
  type TaskSubtask,
  type TaskCommentDto,
  type TaskActivityDto,
  type TaskAttachmentDto,
  type ProjectFileDto,
  type TaskLabelDto,
  type TaskDepRefDto,
  type TaskDepEdgeDto,
  type TaskInput,
  type TaskPriority,
  type SpaceDto,
  type SpaceDetailDto,
  type SpaceMemberDto,
  type SpaceRole,
  type DriveNodeDto,
  type DriveNodeKind,
  type DriveVersionDto,
  type BaseDto,
  type BaseTableDto,
  type BaseFieldDto,
  type BaseViewDto,
  type BaseRecordDto,
  type BaseFieldType,
  type BaseViewKind,
  type SearchHitDto,
  type AiAnswerDto,
  type AgentAnswerDto,
  type AgentActionDto,
  type AgentExecuteResultDto,
  type AgentResultDto,
  type AnomalyFindingDto,
  type CategoryProposalsResultDto,
  type JournalAnomaliesResultDto,
  type ReorderProposalsResultDto,
  type StockAnswerResultDto,
  type WhoIsOffResultDto,
  type VatSummaryResultDto,
  type VatSummarySideDto,
  type ProjectStatusResultDto,
  type TimeEntryResultDto,
  type TimesheetDraftResultDto,
  type ShareableGroup,
  type SharedMailbox,
  type Delegate,
  type SendMode,
} from "./types";
