-- Initial message-store schema. Every tenant-owned table carries
-- tenant_id and a (tenant_id, ...)-leading index so the tenant
-- predicate the TenantStore always adds is an index seek.
--
-- Ids are opaque, random, URL-safe strings generated by the app — no
-- sequential integers cross the API boundary.

-- The isolation root.
CREATE TABLE tenants (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- A user within a tenant (a JMAP "account").
CREATE TABLE users (
    id         TEXT PRIMARY KEY,
    tenant_id  TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    email      TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, email)
);
CREATE INDEX users_tenant ON users(tenant_id);

-- A thread (JMAP Thread): a set of related messages.
CREATE TABLE threads (
    id           TEXT PRIMARY KEY,
    tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    subject_base TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX threads_tenant_subject ON threads(tenant_id, subject_base);

-- Hierarchical mailboxes owned by a user, with transactional counters.
CREATE TABLE mailboxes (
    id              TEXT PRIMARY KEY,
    tenant_id       TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_id       TEXT REFERENCES mailboxes(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    role            TEXT,
    total_messages  BIGINT NOT NULL DEFAULT 0,
    unread_messages BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX mailboxes_tenant_user ON mailboxes(tenant_id, user_id);
-- Sibling names are unique within a user's tree.
CREATE UNIQUE INDEX mailboxes_unique_name
    ON mailboxes(tenant_id, user_id, COALESCE(parent_id, ''), name);
-- JMAP roles (inbox/sent/...) are singletons per user.
CREATE UNIQUE INDEX mailboxes_unique_role
    ON mailboxes(tenant_id, user_id, role) WHERE role IS NOT NULL;

-- Content-addressed blob metadata; the bytes live in Garage at
-- <tenant_id>/<hash>. refcount = 0 marks a blob for a later GC sweep.
CREATE TABLE blobs (
    id         TEXT PRIMARY KEY,
    tenant_id  TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    hash       TEXT NOT NULL,
    size       BIGINT NOT NULL,
    refcount   BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, hash)
);
CREATE INDEX blobs_gc ON blobs(tenant_id) WHERE refcount = 0;

-- Message metadata; the raw RFC 5322 bytes are the referenced blob.
-- Parsed Authentication-Results (RFC 8601) is stored queryable.
CREATE TABLE messages (
    id             TEXT PRIMARY KEY,
    tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id        TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    thread_id      TEXT NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    blob_id        TEXT NOT NULL REFERENCES blobs(id),
    message_id_hdr TEXT,
    subject        TEXT NOT NULL DEFAULT '',
    from_addr      TEXT NOT NULL DEFAULT '',
    to_addrs       TEXT NOT NULL DEFAULT '',
    sent_at        TIMESTAMPTZ,
    received_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    size           BIGINT NOT NULL,
    auth_spf       TEXT,
    auth_dkim      TEXT,
    auth_dmarc     TEXT,
    auth_raw       TEXT,
    search         tsvector,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX messages_tenant_thread ON messages(tenant_id, thread_id);
CREATE INDEX messages_tenant_msgid ON messages(tenant_id, message_id_hdr);
CREATE INDEX messages_search ON messages USING GIN(search);

-- Message ↔ mailbox membership (a message may be in several mailboxes).
CREATE TABLE mailbox_messages (
    tenant_id  TEXT NOT NULL,
    mailbox_id TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
    message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    added_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (mailbox_id, message_id)
);
-- The hot query: list a mailbox newest-first, tenant-scoped.
CREATE INDEX mailbox_messages_listing
    ON mailbox_messages(tenant_id, mailbox_id, added_at DESC);
CREATE INDEX mailbox_messages_by_message
    ON mailbox_messages(tenant_id, message_id);

-- JMAP keywords / IMAP flags, per message (shared across mailboxes).
CREATE TABLE message_keywords (
    tenant_id  TEXT NOT NULL,
    message_id TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    keyword    TEXT NOT NULL,
    PRIMARY KEY (message_id, keyword)
);
CREATE INDEX message_keywords_tenant ON message_keywords(tenant_id, message_id);
