//! # alo-jmap — the JMAP API (RFC 8620 core, RFC 8621 mail)
//!
//! An HTTP service over [`alo_store`]. **A public contract from
//! merge:** the web app, desktop cache, and compat adapters speak it, so
//! every surface changes additively forever (see
//! `docs/design/jmap-api.md`).
//!
//! Every request reaches data only through the store's `for_account`
//! door: the bearer token resolves to `(tenant, account)` via
//! [`alo_identity`] and the tenant claim is never read from a request
//! body. The OpenID Connect / OAuth 2.0 provider is mounted alongside
//! (see [`server::app`]), so one HTTP service serves both JMAP and the
//! IdP.

pub mod admin;
pub mod agent;
pub mod agent_agenda;
pub mod agent_args;
pub mod agent_attachments;
pub mod agent_billing;
pub mod agent_correspondence;
pub mod agent_crm;
pub mod agent_directory;
pub mod agent_docs;
pub mod agent_drive;
pub mod agent_finance;
pub mod agent_finance_answers;
pub mod agent_hr;
pub mod agent_insights;
pub mod agent_inventory;
pub mod agent_meet;
pub mod agent_meeting;
mod agent_orchestrate;
pub mod agent_projects;
pub mod agent_reads;
pub mod agent_sheets;
pub mod agent_sites;
pub mod agent_tasks;
pub mod agent_timesheet;
mod agent_turn;
pub mod ai;
pub mod api;
pub mod app_passwords;
pub mod audit;
pub mod audit_action;
pub mod audit_record;
pub mod autoconfig;
pub mod base;
pub mod billing;
pub mod billing_bills;
pub mod billing_cii;
pub mod billing_customers;
pub mod billing_document;
pub mod billing_einvoice;
pub mod billing_einvoice_rules;
pub mod billing_fx;
pub mod billing_intents;
pub mod billing_invoices;
pub mod billing_pain001;
pub mod billing_pain001_rules;
pub mod billing_payments;
pub mod billing_pdf;
pub mod billing_print;
pub mod billing_products;
pub mod billing_quote_designs;
pub mod billing_quotes;
pub mod billing_reminder;
pub mod billing_reports;
pub mod billing_schedules;
pub mod billing_send;
pub mod billing_sepa;
pub mod billing_settings;
pub mod billing_ubl;
pub mod billing_xml;
pub mod billing_xrechnung_rules;
pub mod blob;
pub mod calendar;
pub mod campaign_audience;
pub mod campaign_consent;
pub mod campaign_preview;
pub mod campaign_record;
pub mod campaign_segments;
pub mod campaign_suppression;
pub mod campaign_unsubscribe;
pub mod campaigns;
pub mod carddav;
pub mod chat;
pub mod chat_agent;
pub mod chat_agent_memory;
pub mod chat_agent_names;
pub mod chat_agent_routes;
pub mod chat_intents;
pub mod chat_turns;
pub mod contacts;
pub mod crm;
pub mod crm_activities;
pub mod crm_deals;
pub mod crm_handoff;
pub mod crm_imports;
pub mod crm_intents;
pub mod crm_next_steps;
pub mod crm_pipelines;
pub mod crm_reports;
pub mod crm_stages;
pub mod crm_threads;
pub mod csv;
pub mod delegates;
pub mod docs;
pub mod docs_intents;
pub mod document_mail;
pub mod drafts;
pub mod drive;
pub mod drive_intents;
pub mod error;
pub mod filters;
pub mod finance_approvals;
pub mod finance_bank;
pub mod finance_bank_match;
pub mod finance_chart;
pub mod finance_chart_names;
pub mod finance_expenses;
pub mod finance_intents;
pub mod finance_mileage;
pub mod finance_periods;
pub mod finance_receipts;
pub mod finance_report_aged;
pub mod finance_report_balance;
pub mod finance_report_pl;
pub mod finance_report_vat;
pub mod finance_reports;
pub mod flagdue;
pub mod hr_checklists;
pub mod hr_documents;
pub mod hr_employees;
pub mod hr_holidays;
pub mod hr_leave_balances;
pub mod hr_leave_door;
pub mod hr_leave_policies;
pub mod hr_leave_requests;
pub mod hr_letters;
pub mod hr_org;
pub mod hr_payroll;
pub mod hr_recruitment;
pub mod imap_import;
pub mod imap_import_route;
pub mod insights;
pub mod insights_ask;
pub mod insights_eval;
pub mod insights_gallery;
pub mod insights_intents;
pub mod inventory_counts;
pub mod inventory_intents;
pub mod inventory_location_names;
pub mod inventory_locations;
pub mod inventory_moves;
pub mod inventory_order_book;
pub mod inventory_po;
pub mod inventory_po_print;
pub mod inventory_po_receipts;
pub mod inventory_po_send;
pub mod inventory_reorder;
pub mod inventory_scan;
pub mod inventory_so;
pub mod inventory_so_deliveries;
pub mod inventory_so_invoice;
pub mod inventory_stock;
pub mod inventory_supplier_prices;
pub mod inventory_suppliers;
pub mod invite_route;
pub mod jtypes;
pub mod junk_learn;
pub mod meet_intents;
pub mod meet_routes;
pub mod meet_token;
// Writing outbound MIME moved down to `alo-store`, beside the reader and for
// the same reason: MAPI composes messages too, and one message format written
// two ways is two formats. Re-exported so `crate::mime::` still names it.
pub use alo_store::mime_write as mime;
// Reading stored MIME moved down to `alo-store`, where the messages are:
// MAPI serves the same bytes JMAP does, and a copy of the parser in each
// protocol crate would be two answers to what a message says. Re-exported
// so `crate::mime_read::` still names it.
pub use alo_store::mime_read;
pub mod module_access;
pub mod projects;
pub mod projects_clients;
pub mod projects_intents;
pub mod projects_invoices;
pub mod projects_plan;
pub mod projects_reports;
pub mod projects_templates;
pub mod projects_time;
pub mod projects_updates;
pub mod projects_weeks;
pub mod push;
pub mod push_notify;
pub mod push_subscriptions;
pub mod quote_design;
pub mod quote_design_images;
pub mod quote_design_lists;
pub mod quote_design_pdf;
pub mod quote_design_print;
pub mod readiness;
pub mod reset_route;
pub mod rich_text;
pub mod schedule;
pub mod scoped_roles;
pub mod security;
pub mod server;
pub mod session;
pub mod settings;
pub mod share;
pub mod sheets_intents;
pub mod sieve;
pub mod signup_route;
pub mod site_booking_notify;
pub mod site_chat_notify;
pub mod site_domain_worker;
pub mod site_notify;
pub mod site_order_notify;
pub mod site_protection;
pub mod site_publish_worker;
pub mod site_schedule;
pub mod site_stock_worker;
pub mod site_ticket_mail;
pub mod site_ticket_worker;
pub mod site_version_preview;
pub mod site_versions;
pub mod sites;
pub mod sites_attribution;
pub mod sites_bookings;
pub mod sites_catalogs;
pub mod sites_chat;
pub mod sites_conversions;
pub mod sites_domain_purchases;
pub mod sites_heatmap;
pub mod sites_knowledge;
pub mod sites_orders;
pub mod sites_palette;
pub mod sites_shop_config;
pub mod sites_shop_items;
pub mod sites_shop_settings;
pub mod sites_templates;
pub mod sites_tickets;
pub mod snooze;
pub mod spaces;
pub mod state;
pub mod submission;
pub mod tasks;
pub mod unsubscribe;
pub mod web_push;
pub mod wopi;
pub mod workspace_search;

pub use push::PushHub;
pub use server::{app, app_state, app_with_site_boundaries, app_with_site_domain_dns, serve};
pub use state::{AppState, Limits};
